easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\User
       - App\Entity\Cat
       - App\Entity\Answer
       - App\Entity\Choice
       - App\Entity\Question
       - App\Entity\Survey